<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],[2,3,4]])
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr2 = np.arange(2,16,2) # start ,stop,step
arr2

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
arr3 = np.linspace(0,1,5) # start,end , number values - evenly spaced
arr3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr4 = np.logspace(1,4,5) # start,end powers , numbers
arr4

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [ ]:
arr5 = np.zeros((2,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr6 = np.ones((2,3))
arr6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr6 = np.ones([2,3], dtype=int)
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr6 = np.full([2,3], 34)
arr6

array([[34, 34, 34],
       [34, 34, 34]])

In [ ]:
arr7 = np.random.randint(10,20)
arr7

11

In [ ]:
arr8 = np.random.randint(10,20 ,size = (2,3)) # start, end , dimentions or size

array([[10, 11, 14],
       [11, 11, 15]])

Array Methods

In [ ]:
#  to create a NumPy array containing evenly spaced values within a specified interval
arr9 = np.arange(3,15,2)
arr9

array([ 3,  5,  7,  9, 11, 13])

In [ ]:
arr9.min()

np.int64(3)

In [ ]:
#  Global NumPy function
minimum_val = np.min(arr9)
minimum_val

np.int64(3)

In [ ]:
# Array method
minimum_val = arr9.min()
minimum_val

np.int64(3)

In [ ]:
arr9.max()

np.int64(13)

In [ ]:
arr9.sum()

np.int64(48)

In [ ]:
int(arr9.sum())

48

In [ ]:
np.sum(arr9,axis=0)

np.int64(48)

In [ ]:
arr10 =arr9.reshape(2,3)
arr10

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [ ]:
# column wise ---axis =0
np.sum(arr10,axis=0)

array([12, 16, 20])

In [ ]:
# row wise -- axis =1
np.sum(arr10,axis=1)

array([15, 33])

In [ ]:
int(arr10.mean())

8

In [ ]:
int(arr10.std())

3

In [ ]:
# maximun element's index
int(arr10.argmax())

5

Reshaping and resizing

In [ ]:
arr= np.arange(1,41)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [ ]:
# 5,6 --- 5 rows and 6 columns ---> there multipication should be the total number of elements in array you want to reshape
arr = arr.reshape(5,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

Array Indexing

In [ ]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
int(arr[3])

4

In [ ]:
arr[::2]

array([1, 3, 5, 7, 9])

In [ ]:
arr = arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Matrix indexing

In [ ]:
arr[2]

array([7, 8, 9])

In [ ]:
arr[1,2]

np.int64(6)

In [ ]:
# to print 2nd column
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
# to print 2,3 and 5,6
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

Boolean indexing

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

Array Operation

Arithmetic operations

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([11,12,13,14,15])

In [ ]:
a1

array([11, 12, 13, 14, 15])

In [ ]:
a1 + a2

array([12, 14, 16, 18, 20])

In [ ]:
a1 - a2

array([-10, -10, -10, -10, -10])

In [ ]:
a1 * a2

array([11, 24, 39, 56, 75])

In [ ]:
a1 / a2

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333])

In [ ]:
a1 % a2

array([1, 2, 3, 4, 5])

In [ ]:
a2 % a1

array([0, 0, 1, 2, 0])

In [ ]:
a2 // a1

array([11,  6,  4,  3,  3])

In [ ]:
a2 ** a1

array([    11,    144,   2197,  38416, 759375])

Broadcasting

In [ ]:
l = [1,2,3,4,5]
arr= np.array(l)
arr

array([1, 2, 3, 4, 5])

In [ ]:
#  to add 10 in each element

# for list
for i in range(len(l)):
    l[i] += 5
print(l)

[6, 17, 8, 9, 10]


In [ ]:
# or
new_l = [x + 5 for x in l]
new_l

[6, 17, 8, 9, 10]

In [ ]:
#  for array
arr + 10

array([11, 12, 13, 14, 15])

Deep and shallow copy

In [ ]:
# list
a =[1,2,3,4,5]
type(a)

list

In [ ]:
# changing in sliced part will change in original is called shallow

In [ ]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [ ]:
arr2 = arr
arr2

array([1, 2, 3, 4])

In [ ]:
arr2[0]= 100
arr2

array([100,   2,   3,   4])

In [ ]:
# also changed in original array
arr

array([100,   2,   3,   4])

Matrix Opearations

In [6]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])


In [7]:
A

array([[1, 2],
       [3, 4]])

In [8]:
B

array([[10, 20],
       [30, 40]])

In [4]:
# normal multiplication NOT MATRIX MULTIPLICATION
A*B

array([[ 10,  40],
       [ 90, 160]])

In [5]:
# this is a matirx multiplication
A @ B

array([[ 70, 100],
       [150, 220]])

In [9]:
# OR
np.dot(A,B)

array([[ 70, 100],
       [150, 220]])

In [11]:
# TRANSPOSE
B.T

array([[10, 30],
       [20, 40]])

Stacking array

In [13]:
# need to use vectors not arrays
C = np.array([1,2,3,4])
D = np.array([5,6,7,8])

In [14]:
np.vstack((C,D))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.hstack((C,D))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.column_stack((C,D))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array

In [18]:
E = np.arange(16).reshape(4,4)
E

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.hsplit(E,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [22]:
np.vsplit(E,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]