<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [12]:
arr = np.array([[1,2,3],[2,3,4]])
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr2 = np.arange(2,16,2) # start ,stop,step
arr2

array([ 2,  4,  6,  8, 10, 12, 14])

In [ ]:
arr3 = np.linspace(0,1,5) # start,end , number values - evenly spaced
arr3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr4 = np.logspace(1,4,5) # start,end powers , numbers
arr4

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [ ]:
arr5 = np.zeros((2,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr6 = np.ones((2,3))
arr6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr6 = np.ones([2,3], dtype=int)
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr6 = np.full([2,3], 34)
arr6

array([[34, 34, 34],
       [34, 34, 34]])

In [ ]:
arr7 = np.random.randint(10,20)
arr7

11

In [ ]:
arr8 = np.random.randint(10,20 ,size = (2,3)) # start, end , dimentions or size

array([[10, 11, 14],
       [11, 11, 15]])

Array Methods

In [10]:
#  to create a NumPy array containing evenly spaced values within a specified interval
arr9 = np.arange(3,15,2)
arr9

array([ 3,  5,  7,  9, 11, 13])

In [14]:
arr9.min()

np.int64(3)

In [15]:
#  Global NumPy function
minimum_val = np.min(arr9)
minimum_val

np.int64(3)

In [16]:
# Array method
minimum_val = arr9.min()
minimum_val

np.int64(3)

In [17]:
arr9.max()

np.int64(13)

In [18]:
arr9.sum()

np.int64(48)

In [20]:
int(arr9.sum())

48

In [22]:
np.sum(arr9,axis=0)

np.int64(48)

In [24]:
arr10 =arr9.reshape(2,3)
arr10

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [25]:
# column wise ---axis =0
np.sum(arr10,axis=0)

array([12, 16, 20])

In [26]:
# row wise -- axis =1
np.sum(arr10,axis=1)

array([15, 33])

In [28]:
int(arr10.mean())

8

In [29]:
int(arr10.std())

3

In [30]:
# maximun element's index
int(arr10.argmax())

5

Reshaping and resizing

In [33]:
arr= np.arange(1,41)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [36]:
# 5,6 --- 5 rows and 6 columns ---> there multipication should be the total number of elements in array you want to reshape
arr = arr.reshape(5,8)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40]])

Array Indexing

In [43]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
int(arr[3])

4

In [45]:
arr[::2]

array([1, 3, 5, 7, 9])

In [46]:
arr = arr.reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Matrix indexing

In [47]:
arr[2]

array([7, 8, 9])

In [48]:
arr[1,2]

np.int64(6)

In [50]:
# to print 2nd column
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [51]:
# to print 2,3 and 5,6
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

Boolean indexing

In [57]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
bool_index = arr % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [59]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

Array Operation