<a href="https://colab.research.google.com/github/hitesh-bhusara/machine-learning/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[2,3,4]])
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
arr2 = np.arange(2,16,2) # start ,stop,step
arr2

array([ 2,  4,  6,  8, 10, 12, 14])

In [5]:
arr3 = np.linspace(0,1,5) # start,end , number values - evenly spaced
arr3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
arr4 = np.logspace(1,4,5) # start,end powers , numbers
arr4

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [7]:
arr5 = np.zeros((2,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
arr6 = np.ones((2,3))
arr6

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr6 = np.ones([2,3], dtype=int)
arr6

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
arr6 = np.full([2,3], 34)
arr6

array([[34, 34, 34],
       [34, 34, 34]])

In [11]:
arr7 = np.random.randint(10,20)
arr7

11

In [12]:
arr8 = np.random.randint(10,20 ,size = (2,3)) # start, end , dimentions or size

array([[10, 11, 14],
       [11, 11, 15]])

Numpy Data Types and Type Casting


